### ISSUE TITLE
Правки по ЛР3

### ISSUE THREAD

**Issue by shchuko** [shchuko/ifmo-weather-rest#3]
- [x] перенести секреты в переменные среды
- [x] использовать облачную бд от mongo
- [x] задеплоить бэк на амазон
- [ ] ~прикрутить ssl-сертификат к бэку (AWS Certificate Manager не завелся, вероятно, делать не стану)~
- [x] переключить github pages на свой бэк ~(временно сделано, но ругается на  https+http)~
- [x] перенести бэк на heroku

**Comment by BakasaRus** [comment]
Вот чего ещё накину:

- [x] Может, везде стоит использовать `async/await` вместо `then()` и `catch()`?
- [x] В Express есть [обработка ошибок](https://expressjs.com/ru/guide/error-handling.html) без повсеместного `try` / `catch`, было б неплохо её заюзать;
- [x] Если хочешь несколько файлов с маршрутами, то можно сделать по [этой доке](https://expressjs.com/ru/guide/routing.html);
- [x] На создание ресурса можно кидать 201, а не 200;
- [x] `JSUnfilteredForInLoop` обычно фиксится через метод `hasOwnProperty()` у итерируемого объекта;
- [x] При добавлении карточки на мгновение появляется название города из поля ввода, потом оно заменяется на название из API;
- [x] При удалении города он удаляется дважды: с именем из API и с именем, по которому его добавили;
- [x] Может, стоит логику работы с MongoDB закинуть куда-нибудь отдельно, чтобы не крутилась в контроллере.

Заметил ещё спецэффект: город добавляется не в конец, а в начало. Это баг или фича?

**Comment by shchuko** [comment]
1. > В Express есть обработка ошибок без повсеместного try / catch, было б неплохо её заюзать

Использовал `express-async-handler`

2. > При добавлении карточки на мгновение появляется название города из поля ввода, потом оно заменяется на название из API

Это же замечание было и по второй работе, так сделано согласно макету: надо на время ожидания ответа от сервера повесить карточку с именем города и "загрузкой":

![image](https://user-images.githubusercontent.com/36963534/114098832-97a63500-98ca-11eb-9465-1066efcbd0c0.png)
 
Так и делаю, но пока корректное имя неизвестно - вешаю то, что в запросе. 

3. > При удалении города он удаляется дважды: с именем из API и с именем, по которому его добавили

Воспроизвести не получилось, но я уже основательно отрефакторил работу с БД, подобного поведения сейчас нет (если я чего-то не упустил)

4. > Заметил ещё спецэффект: город добавляется не в начало, а в конец. Это баг или фича?

Фича)

**Comment by BakasaRus** [comment]
Посмотри насчёт удаления, что имелось в виду

https://user-images.githubusercontent.com/21131366/114139742-17a6bc00-9918-11eb-9627-7bfaa0a86c3c.mp4

**Comment by shchuko** [comment]
Интересное поведение, проблема оказалась в повторном вызове обработчика нажатия кнопки здесь:

![image](https://user-images.githubusercontent.com/36963534/114151298-a66e0580-9925-11eb-91e5-82cbe07e022b.png)

Лямбда вызывается дважды. Пойду разбираться

**Comment by shchuko** [comment]
> При удалении города он удаляется дважды: с именем из API и с именем, по которому его добавили;

[~fixed~](https://github.com/shchuko/ifmo-weather/commit/95edd86a4b1f206b6252f53692c968e29dae9f49), неа, еще поломано

**Comment by shchuko** [comment]
> При удалении города он удаляется дважды: с именем из API и с именем, по которому его добавили;

вот теперь [fixed](https://github.com/shchuko/ifmo-weather/commit/2ee94462962e08c61a941017eef38c962b756ab8)
